version: '3.8'
services:
  autopdf:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GLPI_URL=https://ltimindtree.in1.glpi-network.cloud
      - GLPI_APP_TOKEN=bnVEfEQ6n7kYpzFCEiF1UgCCWJkd5bWyU7UiQXd3
      - GLPI_USER_TOKEN=hN04d5lgFrkmprGz183sPfUhXt04102DF10pUFsN
      - MEILISEARCH_URL=https://ms-6c0bfee744cb-18789.nyc.meilisearch.io
      - MEILISEARCH_MASTER_KEY=289e33eaa93280a3955fbed03a73fce65048d51c
      - WASABI_ENDPOINT=https://s3.ap-northeast-1.wasabisys.com
      - WASABI_ACCESS_KEY=WFDR91CL1S6EII3LFKHV
      - WASABI_SECRET_KEY=rGnTDbiXOm3IFpRiaAZm9jGkfXJTGpylrJbuZ0et
      - OPENAI_API_BASE=https://chatapi.akash.network/api/v1
      - OPENAI_API_KEY=sk-lw2UYlqYhjaXkboZ0pHv9A
      - MODEL_NAME=DeepSeek-R1
      - BUCKET_NAME=rapidwrite
